### ISSUE TITLE
I have some questions about command 'screen'

### ISSUE THREAD

**Issue by stevebobaaa** [snkas/exputilpy#3] opened 2022-11-07 08:30 UTC
FAILED tests/test_shell_basic.py::TestBasic::test_local_shell_screens - exputil.shell.InvalidCommandError: ('/bin/sh: 1: screen: not found\n', <exp...
Thank you so much!

**Comment by snkas** [comment] 2022-11-11 12:47
Duplicate of https://github.com/snkas/exputilpy/issues/2

**Closed as completed by snkas** 2022-11-11 12:47 UTC
